input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    ssl_verification_mode => "none"
    user => "elastic"
    password => "MztZE-MXSmpqMcAhZqFF"
    index => "%{[kubernetes][container][name]}"
  }
}
