input {
  beats {
    port => 5044
  }
}

filter {
 if [kubernetes][container][name] == "frontend" {
  grok {
    match => { "message" => "%{IP:ip}%{SPACE}%{HTTPDATE}%{SPACE}%{WORD:http_method}%{SPACE}%{PATH:http_path}%{SPACE}%{WORD}/%{NUMBER}%{SPACE}%{NUMBER:http_code}%{SPACE}%{NUMBER:response_time}%{SPACE}%{NUMBER:response_size}%{SPACE}%{QUOTEDSTRING:http_referer}%{SPACE}%{QUOTEDSTRING:http_user_agent}%{SPACE}%{QUOTEDSTRING:http_x_forwarded_for}" }
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    ssl_verification_mode => "none"
    user => "elastic"
    password => "MztZE-MXSmpqMcAhZqFF"
    index => "%{[kubernetes][container][name]}"
  }
}
